"""create liturgias table

Revision ID: f0b0a1a3757d
Revises: 
Create Date: 2025-10-03 21:13:58.126016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0b0a1a3757d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liturgias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('primeira_leitura', sa.String(), nullable=False),
    sa.Column('salmo_responsorial', sa.String(), nullable=False),
    sa.Column('segunda_leitura', sa.String(), nullable=True),
    sa.Column('evangelho', sa.String(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('liturgias')
    # ### end Alembic commands ###
